downgrade AngularJS to 1.6.6 due to unit test failures
Since Angular 1.6.7 unexpected HTTP requests in unit tests are passed
to the error handler [1], [2].
This is most like the reason for all failing tests with
Error: Unexpected request: GET /ebegu/api/v1/gesuchsperioden/active

[1] https://github.com/angular/angular.js/blob/master/CHANGELOG.md#167-imperial-backstroke-2017-11-24
[2] https://github.com/angular/angular.js/commit/1555a4911ad5360c145c0ddc8ec6c4bf9a381c13